# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [61]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep="\t")

### Step 4. See the first 10 entries

In [3]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [5]:
# Solution 1

chipo.shape[0]

4622

In [2]:
# Solution 2

### Step 6. What is the number of columns in the dataset?

In [7]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [8]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

### Step 8. How is the dataset indexed?

In [9]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [27]:
most=chipo[['item_name','quantity']].groupby('item_name')["quantity"].sum().sort_values(ascending=False).reset_index()
most

                                item_name  quantity
0                            Chicken Bowl       761
1                         Chicken Burrito       591
2                     Chips and Guacamole       506
3                           Steak Burrito       386
4                       Canned Soft Drink       351
5                                   Chips       230
6                              Steak Bowl       221
7                           Bottled Water       211
8            Chips and Fresh Tomato Salsa       130
9                             Canned Soda       126
10                     Chicken Salad Bowl       123
11                     Chicken Soft Tacos       120
12                          Side of Chips       110
13                         Veggie Burrito        97
14                       Barbacoa Burrito        91
15                            Veggie Bowl        87
16                          Carnitas Bowl        71
17                          Barbacoa Bowl        66
18                       Carnitas Burrito        60
19                       Steak Soft Tacos        56
20                      6 Pack Soft Drink        55
21    Chips and Tomatillo Red Chili Salsa        50
22                   Chicken Crispy Tacos        50
23  Chips and Tomatillo Green Chili Salsa        45
24                    Carnitas Soft Tacos        40
25                     Steak Crispy Tacos        36
26  Chips and Tomatillo-Green Chili Salsa        33
27                       Steak Salad Bowl        31
28                       Nantucket Nectar        29
29    Chips and Tomatillo-Red Chili Salsa        25
30                    Barbacoa Soft Tacos        25
31     Chips and Roasted Chili Corn Salsa        23
32                                   Izze        20
33                      Veggie Salad Bowl        18
34     Chips and Roasted Chili-Corn Salsa        18
35                  Barbacoa Crispy Tacos        12
36                    Barbacoa Salad Bowl        10
37                          Chicken Salad         9
38                  Carnitas Crispy Tacos         8
39                      Veggie Soft Tacos         8
40                                Burrito         6
41                           Veggie Salad         6
42                    Carnitas Salad Bowl         6
43                                   Bowl         4
44                            Steak Salad         4
45                                  Salad         2
46                           Crispy Tacos         2
47      Chips and Mild Fresh Tomato Salsa         1
48                         Carnitas Salad         1
49                    Veggie Crispy Tacos         1

### Step 10. For the most-ordered item, how many items were ordered?

In [32]:
print(most.loc[0,'quantity'])

761

### Step 11. What was the most ordered item in the choice_description column?

tried two ways :

In [46]:
chipo["choice_description"].value_counts().sort_values(ascending=False)

choice_description
[Diet Coke]                                                                                                                     134
[Coke]                                                                                                                          123
[Sprite]                                                                                                                         77
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Lettuce]]                                                           42
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]                                                40
                                                                                                                               ...
[Roasted Chili Corn Salsa, [Rice, Fajita Vegetables]]                                                                             1
[Tomatillo Green Chili Salsa, [Rice, Fajita Vegetables, Sour Cream]]                                                              1
[Fresh Tomato Salsa, [Rice, Fajita Vegetables, Pinto Beans, Cheese]]                                                              1
[[Roasted Chili Corn Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Pinto Beans, Rice, Fajita Veggies, Cheese, Lettuce]]      1
[Tomatillo Green Chili Salsa, [Rice, Fajita Vegetables, Black Beans, Guacamole]]                                                  1
Name: count, Length: 1043, dtype: int64

In [44]:
choices = chipo["choice_description"].to_list()
desc_list = [[item.strip() for item in str(x).split(",")] for x in choices]
pd.Series(desc_list).value_counts()

[nan]                                                                                                   1246
[[Diet Coke]]                                                                                            134
[[Coke]]                                                                                                 123
[[Sprite]]                                                                                                77
[[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Lettuce]]]                                  42
                                                                                                        ...
[[Tomatillo Red Chili Salsa, [Rice, Fajita Vegetables, Black Beans, Sour Cream, Cheese, Guacamole]]]       1
[[Roasted Chili Corn Salsa, [Rice, Sour Cream, Cheese, Lettuce, Guacamole]]]                               1
[[Roasted Chili Corn Salsa, [Pinto Beans, Sour Cream, Cheese, Lettuce, Guacamole]]]                        1
[[Tomatillo Green Chili Salsa, [Rice, Black Beans]]]                                                       1
[[Tomatillo Green Chili Salsa, [Rice, Fajita Vegetables, Black Beans, Guacamole]]]                         1
Name: count, Length: 1044, dtype: int64

### Step 12. How many items were orderd in total?

In [48]:
chipo["quantity"].sum()

np.int64(4972)

### Step 13. Turn the item price into a float

In [ ]:
chipo["item_price_float"] = chipo["item_price"].str.replace("$","").astype(float)

#### Step 13.a. Check the item price type

In [63]:
print(chipo["item_price_float"].dtypes)
print(chipo["item_price"].dtypes)

float64
str

#### Step 13.b. Create a lambda function and change the type of item price

In [65]:
chipo["item_price"]= chipo["item_price"].apply(lambda x : float(x.replace('$','')))

#### Step 13.c. Check the item price type

In [66]:
chipo["item_price"].dtypes

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [68]:
chipo["revenue"] = chipo["item_price"]* chipo['quantity']
print(chipo["revenue"].head())
print(chipo["revenue"].sum())

0     2.39
1     3.39
2     3.39
3     2.39
4    33.96
Name: revenue, dtype: float64
39237.02

### Step 15. How many orders were made in the period?

In [75]:
orders = chipo["order_id"].nunique()

### Step 16. What is the average revenue amount per order?

In [80]:
# Solution 1
chipo.groupby("order_id")["revenue"].sum().mean()

np.float64(21.39423118865867)

In [78]:
# Solution 2
mean = chipo["revenue"].sum() / orders
mean

np.float64(21.39423118865867)

### Step 17. How many different items are sold?

In [81]:
chipo["item_name"].nunique()

50