# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [2]:
drinks = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv")

In [3]:
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

### Step 4. Which continent drinks more beer on average?

In [5]:
drinks.groupby("country")["beer_servings"].mean().sort_values(ascending=False)

country
Namibia           376.0
Czech Republic    361.0
Gabon             347.0
Germany           346.0
Lithuania         343.0
                  ...
Kuwait              0.0
Iran                0.0
Cook Islands        0.0
Bangladesh          0.0
Libya               0.0
Name: beer_servings, Length: 193, dtype: float64

### Step 5. For each continent print the statistics for wine consumption.

In [8]:
drinks.groupby("country")["wine_servings"].describe()

             count   mean  std    min    25%    50%    75%    max
country
Afghanistan    1.0    0.0  NaN    0.0    0.0    0.0    0.0    0.0
Albania        1.0   54.0  NaN   54.0   54.0   54.0   54.0   54.0
Algeria        1.0   14.0  NaN   14.0   14.0   14.0   14.0   14.0
Andorra        1.0  312.0  NaN  312.0  312.0  312.0  312.0  312.0
Angola         1.0   45.0  NaN   45.0   45.0   45.0   45.0   45.0
...            ...    ...  ...    ...    ...    ...    ...    ...
Venezuela      1.0    3.0  NaN    3.0    3.0    3.0    3.0    3.0
Vietnam        1.0    1.0  NaN    1.0    1.0    1.0    1.0    1.0
Yemen          1.0    0.0  NaN    0.0    0.0    0.0    0.0    0.0
Zambia         1.0    4.0  NaN    4.0    4.0    4.0    4.0    4.0
Zimbabwe       1.0    4.0  NaN    4.0    4.0    4.0    4.0    4.0

[193 rows x 8 columns]

### Step 6. Print the mean alcohol consumption per continent for every column

In [11]:
drinks.groupby("country")[['beer_servings','spirit_servings','wine_servings','total_litres_of_pure_alcohol']].mean()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
country,,,,
Afghanistan,0.0,0.0,0.0,0.0
Albania,89.0,132.0,54.0,4.9
Algeria,25.0,0.0,14.0,0.7
Andorra,245.0,138.0,312.0,12.4
Angola,217.0,57.0,45.0,5.9
...,...,...,...,...
Venezuela,333.0,100.0,3.0,7.7
Vietnam,111.0,2.0,1.0,2.0
Yemen,6.0,0.0,0.0,0.1
Zambia,32.0,19.0,4.0,2.5
Zimbabwe,64.0,18.0,4.0,4.7

### Step 7. Print the median alcohol consumption per continent for every column

In [12]:
drinks.groupby("country")[['beer_servings','spirit_servings','wine_servings','total_litres_of_pure_alcohol']].median()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
country,,,,
Afghanistan,0.0,0.0,0.0,0.0
Albania,89.0,132.0,54.0,4.9
Algeria,25.0,0.0,14.0,0.7
Andorra,245.0,138.0,312.0,12.4
Angola,217.0,57.0,45.0,5.9
...,...,...,...,...
Venezuela,333.0,100.0,3.0,7.7
Vietnam,111.0,2.0,1.0,2.0
Yemen,6.0,0.0,0.0,0.1
Zambia,32.0,19.0,4.0,2.5
Zimbabwe,64.0,18.0,4.0,4.7

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [13]:
drinks.groupby("country")['spirit_servings'].agg(["mean",'max','min'])

              mean  max  min
country
Afghanistan    0.0    0    0
Albania      132.0  132  132
Algeria        0.0    0    0
Andorra      138.0  138  138
Angola        57.0   57   57
...            ...  ...  ...
Venezuela    100.0  100  100
Vietnam        2.0    2    2
Yemen          0.0    0    0
Zambia        19.0   19   19
Zimbabwe      18.0   18   18

[193 rows x 3 columns]